#!/usr/bin/env node
/* eslint-disable no-console */

// CommonJS for compatibility with current package.json (no "type": "module").
// Uses Node 18+ native fetch and loads .env.local explicitly.
const path = require("path");
const dotenv = require("dotenv");

const envPath = path.resolve(process.cwd(), ".env.local");
dotenv.config({ path: envPath });

const TOKEN =
  process.env.STORYBLOK_MANAGEMENT_TOKEN || process.env.STORYBLOK_OAUTH_TOKEN;
if (!TOKEN) {
  console.error(
    "Missing STORYBLOK_MANAGEMENT_TOKEN (or STORYBLOK_OAUTH_TOKEN) in .env.local"
  );
  process.exit(1);
}

const SPACE_ID = "288724910612784";
const API_URL = `https://mapi.storyblok.com/v1/spaces/${SPACE_ID}`;

// ---------------------------
// Unsplash image presets
// ---------------------------
const unsplash = {
  thailand: [
    "https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d5",
    "https://images.unsplash.com/photo-1505739772516-aeb5e7b8a229",
    "https://images.unsplash.com/photo-1528181304800-259b08848585",
  ],
  greece: [
    "https://images.unsplash.com/photo-1505731132164-cca7f6b0d63b",
    "https://images.unsplash.com/photo-1508176922333-e8403f2c7a2d",
    "https://images.unsplash.com/photo-1476480862126-209bfaa8edc8",
  ],
  italy: [
    "https://images.unsplash.com/photo-1509358271058-acd22cc93888",
    "https://images.unsplash.com/photo-1502602898657-3e91760cbb34",
  ],
  spain: [
    "https://images.unsplash.com/photo-1509316785289-025f2b2d86cb",
    "https://images.unsplash.com/photo-1483683804023-6ccdb62f86ef",
  ],
  france: [
    "https://images.unsplash.com/photo-1528909514045-2fa4ac7a08ba",
    "https://images.unsplash.com/photo-1495555687392-5f32d12fd87b",
  ],
};

function countryImages(country) {
  return unsplash[country.toLowerCase()] || unsplash.thailand;
}

// ---------------------------
// Simple POST helper
// ---------------------------
async function sbPost(endpoint, body) {
  const res = await fetch(`${API_URL}/${endpoint}`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${TOKEN}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify(body),
  });

  if (!res.ok) {
    const errorBody = await res.text();
    console.error(errorBody);
    throw new Error(`Storyblok error ${res.status} POST ${endpoint}`);
  }

  return res.json();
}

// ---------------------------
// Simple PUT helper
// ---------------------------
async function sbPut(endpoint, body) {
  const res = await fetch(`${API_URL}/${endpoint}`, {
    method: "PUT",
    headers: {
      Authorization: `Bearer ${TOKEN}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify(body),
  });

  if (!res.ok) {
    const errorBody = await res.text();
    console.error(errorBody);
    throw new Error(`Storyblok error ${res.status} PUT ${endpoint}`);
  }

  return res.json();
}

// ---------------------------
// Create a Page: Country
// ---------------------------
async function createCountryPage(country) {
  console.log(`Creating country: ${country}`);

  const [heroImage] = countryImages(country);

  return sbPost("stories", {
    story: {
      name: country,
      slug: country.toLowerCase(),
      content: {
        component: "page_country",
        title: country,
        hero_image: { filename: heroImage },
        description: {
          type: "doc",
          content: [
            {
              type: "paragraph",
              content: [
                {
                  type: "text",
                  text: `${country} autogenerated travel content.`,
                },
              ],
            },
          ],
        },
        body: [],
      },
      is_startpage: false,
      published: true,
    },
  });
}

// ---------------------------
// Create experience_card blok
// ---------------------------
function createExperienceCard(country, index) {
  const images = countryImages(country);
  const img = images[index % images.length];
  const experienceName = `${country} Experience ${index + 1}`;
  const duration = `${2 + index} hours`;
  const price = 50 + index * 10;

  console.log(`   Experience: ${experienceName}`);

  return {
    _uid: Math.random().toString(36).substring(2, 9),
    component: "experience_card",
    title: experienceName,
    image: { filename: img },
    price,
    duration,
    location: country,
    description: `Auto-generated travel experience in ${country}.`,
  };
}

// ---------------------------
// Create Featured Section
// ---------------------------
async function attachFeaturedExperiences(storyId, country) {
  const experiences = [];

  for (let i = 0; i < 5; i += 1) {
    experiences.push(createExperienceCard(country, i));
  }

  console.log(`Attaching Featured Experiences to ${country}`);

  const [heroImage] = countryImages(country);

  return sbPut(`stories/${storyId}`, {
    story: {
      content: {
        component: "page_country",
        title: country,
        hero_image: { filename: heroImage },
        description: {
          type: "doc",
          content: [
            {
              type: "paragraph",
              content: [
                {
                  type: "text",
                  text: `${country} autogenerated travel content.`,
                },
              ],
            },
          ],
        },
        body: [
          {
            _uid: Math.random().toString(36).substring(2, 9),
            component: "featured_experiences_section",
            title: `Featured Experiences in ${country}`,
            experiences,
          },
        ],
      },
    },
    publish: 1,
  });
}

// ---------------------------
// MAIN EXECUTION
// ---------------------------
async function run() {
  console.log("Wanderlast Seeder Running");

  const countries = ["Thailand", "Greece", "Italy", "Spain", "France"];

  for (const country of countries) {
    const created = await createCountryPage(country);
    await attachFeaturedExperiences(created.story.id, country);
  }

  console.log("Seeder complete!");
}

run().catch((err) => {
  console.error(err);
  process.exit(1);
});
